linters:
  enable:
    - megacheck
    - golint
    - govet
    - unconvert
    - megacheck
    - structcheck
    - gas
    - gocyclo
    - dupl
    - misspell
    - unparam
    - varcheck
    - deadcode
    - typecheck
    - ineffassign
    - varcheck
    - stylecheck
    - scopelint
    - gocritic
    - nakedret
    - gosimple
    - prealloc
  fast: false
  disable-all: true